server {
	listen 8081;
	host 127.0.0.1;
	client_max_body_size 1M;
	status_directory ./www/error;
	error_page 404 ./www/error/404.html;
	error_page 500 ./www/error/500.html;

	location / {
		methods GET POST DELETE;
		root ./www;
		index index.html;
		autoindex off;
		upload_store ./www/posts;
	}

	location /old {
		methods GET;
		return 301 /;
	}

	location /listing {
		methods GET;
		root ./www/autoindex;
		autoindex on;
	}

	location /private {
		methods GET;
		root ./www/private;
		autoindex off;
	}

	location /python {
		methods GET POST;
		root ./www;
		cgi_extension .py /usr/bin/python3;
	}
}
